---
  - name: Update `etc/hosts` on the server.
    template: src=etc_hosts dest=/etc/hosts owner=root group=root backup=yes mode=0644

  - name: Update Hostname (/etc/sysconfig/network)
    lineinfile: dest=/etc/sysconfig/network regexp='^HOSTNAME' line="HOSTNAME={{ host_name }}" state=present

  - name: Setting the Hostname Without a restart.
    command: hostname {{ host_name }}
