---
  - name: Create /tmp and /var directories in HDFS.
    command: sh "{{ common['soft_link_base_path'] }}"/hadoop/bin/hadoop fs -mkdir -p {{ item }}
    sudo: yes
    sudo_user: "{{ hadoop_user }}"
    with_items:
      - "/tmp"
      - "/var"
      - "/user/{{ hadoop_user }}"

  - name: Setting Permission for Hadoop /tmp and /var directories.
    command: sh "{{ common['soft_link_base_path'] }}"/hadoop/bin/hadoop fs -chmod 1777 {{ item }}
    sudo: yes
    sudo_user: "{{ hadoop_user }}"
    with_items:
      - "/tmp"
      - "/var"